name:                xmonad-falkjet
version:             0.1.0.0
github:              "falkjet/xmonad"
license:             BSD-3-Clause
author:              "Falk Markus Dursun Jetlund"
maintainer:          "falk@jetlund.com"
copyright:           "2023 Falk Markus Dursun Jetlund"

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- xmonad
- xmonad-contrib
- containers
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  try-haskell:
    main: xmonad.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
